services:
  - type: web
    name: nota-facil-lite
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: JWT_SECRET
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DISABLE_AUTH
        value: "false"
